resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/12.yaml

packages:
  - ./sdk
  - ./example

extra-deps:
  - github: Concordium/http2-client
    commit: 87c4306a624ff490ac9bd92e075ff09f14c341f4

  - github: Concordium/http2-grpc-haskell
    commit: 6787bbe9445e841c02c8b1f699304be15b3c3e5a
    subdirs:
      - http2-client-grpc
      - http2-grpc-proto-lens
      - http2-grpc-types
